#!/bin/bash

# Skripti eesmärk: kontrollida, kas antud täisarv on paaris või paaritu.

echo "See skript kontrollib, kas antud täisarv on paaris või paaritu."
echo "Käivitamiseks sisestage üks argument - täisarv. Näide: $0 4"
echo

# Kontrollime, kas skripti käivitamiseks on antud täpselt üks argument
if [ $# -ne 1 ]; then
    echo "Käivita see skript koos arvuga, mille paarsust soovid kontrollida. Näiteks: $0 3"
    exit 1
fi

arv=$1

# Kontrollime, kas number on paaris või paaritu
jaak=$(( arv % 2 ))
if [ $jaak -eq 0 ]; then
    echo "$arv on paaris."
else
    echo "$arv on paaritu."
fi
